FactoryManagement/Controllers/LeaveManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using FactoryManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System.Xml;
using Newtonsoft.Json;
using System.Collections;
using System.Data.SqlClient;
using System.IO;
using System.Web.Script.Serialization;
using FactoryManagement.ModelView;
using FactoryManagement.ModelView.HR;
using System.Web.Helpers;
using FactoryManagement.ModelView.SalaryConfig;
using System.ComponentModel;
using System.Configuration;
using System.Data.Entity.Core.Objects;

namespace FactoryManagement.Controllers
{
    [Authorize]
    [DisplayName("Leave Management")]
    public class LeaveManagementController : Controller
    {

        #region Private Properties
        private FactoryManagementEntities db = new FactoryManagementEntities();
        private FactoryManagementEntities dbAdu = new FactoryManagementEntities();
        static private int offset = Convert.ToInt32(ConfigurationManager.AppSettings["localTime"]);
        DateTime now = DateTime.UtcNow.AddMinutes(offset);
        const int ShowLeaveUserPerPage = 15;
        #endregion


        //************************ Manually Give Leave  *****************************************
        #region
        public ActionResult LeaveApplication(int? id, string v)
        {
            Leave_Application_List model = new Leave_Application_List();
            if (id != null)
            {
                model = db.Leave_Application_List.Find(id);
            }
            if (v == "p")
            {
                if (model.ApplicationUserId > 0)
                {
                    ViewBag.Empname = db.View_UserLists.Where(m => m.UserId == model.ApplicationUserId).Select(m => m.UserName).FirstOrDefault();
                }
                return PartialView("_LeaveApplication", model);
            }
            return View(model);
        }
        public JsonResult LeaveAppSave(Leave_Application_List model,long userId)
        {
            string name = "Leave Approve";
            string msg = "";
            int ColumnId = 0;
            int status = -1;

            if (ModelState.IsValid)
            {
                model.ApprovedDate = now;
                db.Leave_Application_List.Add(model);
                try
                {
                    db.SaveChanges();
                    msg = "Leave has been successfully approved on " + now.ToString("MMM dd,yyyy hh:mm tt");
                    status = 1;
                    ColumnId =Convert.ToInt32(db.Leave_Application_List.Where(m => m.ApplicationUserId == model.ApplicationUserId && m.ApprovedBy == model.ApprovedBy).Max(m => m.LeaveId));
                }
                catch (Exception)
                {
                    msg = "Leave approve was unsuccessful on "+now.ToString("MMM dd, yyyy hh: mm tt");;
                    status = -1; 
                }
                SaveAuditLog(name, msg, "HR", "Leave Management", "Leave_Application_List", ColumnId, userId, now, status);
                if (status == 1)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
                
            }
            return Json("Error",JsonRequestBehavior.AllowGet);
        }
        public JsonResult EmployeeeNameSearching(string prefix)
        {
            if (prefix == "")
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
            else
            {
                var allUser = (from s in db.View_UserLists
                                  where (s.UserName.ToLower().Contains(prefix.ToLower()))
                                  && s.Status == 1
                                  select new 
                                  {
                                      UserId = s.UserId,
                                      UserName = s.UserName+" (Sitename: "+s.SiteName+" ; EmpId: "+s.EmpId+" )",
                                      Sitename = s.SiteName,
                                      DesignationName = s.DesignationName
                                  }).ToList();
                return Json(allUser, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion


        //************************ Leave  Application  *******************************************
        #region
        public ActionResult LeaveApplicationForm(int? id,long userId)
        {
            Leave_Application_List model = new Leave_Application_List();
            model.ApplicationUserId = userId;
            if (id != null)
            {
                model = db.Leave_Application_List.Find(id);
            }
            return View(model);
        }
        public JsonResult LeaveAppRequestSave(Leave_Application_List model)
        {
            string name = "Leave Application";
            string msg = "";
            int ColumnId = 0;
            int status = -1;

            if (ModelState.IsValid)
            {
                model.AppliedDate = now;
                db.Leave_Application_List.Add(model);
                try
                {
                    db.SaveChanges();
                    msg = "Leave application has been successfully saved.";
                    status = 1;
                    ColumnId = Convert.ToInt32(db.Leave_Application_List.Where(m => m.ApplicationUserId == model.ApplicationUserId).Max(m => m.LeaveId));
                }
                catch (Exception)
                {
                    msg = "Leave application save was unsuccessful.";
                    status = -1;
                }
                SaveAuditLog(name, msg, "HR", "Leave Management", "Leave_Application_List", ColumnId, model.ApplicationUserId, now, status);
                if (status == 1)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }

            }
            return Json("Error", JsonRequestBehavior.AllowGet);
        }
        #endregion


        //************************** All Requested Leave Application *****************************
        #region
        public ActionResult ShowAllRequestedLeaveApplication()
        {
            return View();
        }
        #endregion


        #region
        public PartialViewResult _LeaveAppDetails(int id)
        {
            var model = db.Leave_Application_List.Find(id);
            return PartialView(model);
        }
        #endregion

        //*********************** Edit Leave Application Form ****************************************
        #region
        public PartialViewResult _LeaveAppEdit(int? id)
        {
            ViewBag.id = id;
            return PartialView();
        }
        public JsonResult LeaveAppEdit(Leave_Application_List model)
        {
            string name = "Leave Application Edit";
            string msg = "";
            int ColumnId = 0;
            int status = -1;
            if (model.LeaveId>0)
            {
                Leave_Application_List leave = db.Leave_Application_List.Find(model.LeaveId);
                leave.PreStartDate = leave.StartDate;
                leave.PreEndDate = leave.EndDate;

                leave.StartDate = model.StartDate;
                leave.EndDate = model.EndDate;
                leave.UpdatedDate = now;
                leave.UpdatedBy = model.UpdatedBy;
                leave.Reason = model.Reason;
                db.Entry(leave).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    msg = "Leave application has been successfully upated on "+now.ToString("MMM dd,yyyy hh:mm tt")+".";
                    status = 1;
                    // ColumnId = Convert.ToInt32(db.Leave_Application_List.Where(m => m.ApplicationUserId == model.ApplicationUserId && m.ApprovedBy == model.ApprovedBy).Max(m => m.LeaveId));
                  //Already have the leave application id. 
                    
                    //LeaveId data type is long and ColumnId data type is int.
                    //It may raise problem in long run;
                    ColumnId = (int)model.LeaveId;
                }
                catch (Exception)
                {
                    msg = "Leave application update was unsuccessfulon " + now.ToString("MMM dd,yyyy hh:mm tt") + ".";
                    status = -1;
                }
                SaveAuditLog(name, msg, "HR", "Leave Management", "Leave_Application_List", ColumnId, Convert.ToInt32(model.UpdatedBy), now, status);
                if (status == 1)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }

            }
            return Json("Error", JsonRequestBehavior.AllowGet);
        }
        #endregion

        //*********************** Approve Application Form ****************************************
        #region
        public JsonResult LeaveAppApprove(long? id, long userId)
        {
            string name = "Leave Application Approve";
            string msg = "";
            int status = -1;

            if (id != null)
            {
                Leave_Application_List model = db.Leave_Application_List.Find(id);
                model.ApproveStatus = 1;
                model.ApprovedBy = userId;
                model.ApprovedDate = now;
                db.Entry(model).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    msg = "Leave application has been successfully approved on " + now.ToString("MMM dd, yyyy hh:mm tt") + " .";
                    status = 1;
                }
                catch (Exception)
                {
                    msg = "Leave application approve was unsuccessful on " + now.ToString("MMM dd, yyyy hh:mm tt") + " .";
                    status = -1;

FactoryManagement/Views/LeaveManagement/LeaveApplicationForm.cshtml
@************************************** Created By Jerin Jahan (Date:12.01.2017)  ***************************************@

@model FactoryManagement.Models.Leave_Application_List
@{
    ViewBag.Title = "LeaveApplication";
    Layout = "~/Views/Shared/_LayoutForTemplate.cshtml";
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-users fa-fwt"></i>
            <span>Leave Management</span>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <i class="fa fa-file-text" aria-hidden="true"></i>
            <span>Leave Applicaion Form</span>
        </li>
    </ul>
</div>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-fit bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-file-text-o font-green" aria-hidden="true"></i>
                        <span class="caption-subject font-green bold uppercase">Leave Application Form</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-horizontal" id="div_Leave_App">
                                <input id="DateValidation" name="DateValidation" type="hidden">
                                <div class="form-horizontal  col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ApplicationUserId, "Start Date", htmlAttributes: new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-7">
                                            @(Html.Kendo().DatePicker().Name("StartDate").Format("MMM dd,yyyy").Min(DateTime.Now).HtmlAttributes(new { style = "width: 100%" }))
                                            <span class="field-validation-valid text-danger" data-valmsg-for="StartDate" data-valmsg-replace="true"></span>
                                            <span class="field-validation-valid text-danger" data-valmsg-for="DateValidation" data-valmsg-replace="true"></span>
                                        </div>
                                        <label class="control-label col-lg-1 col-md-1 col-sm-3 col-xs-12">To</label>
                                        <div class="col-lg-4 col-md-4 col-sm-5 col-xs-7">
                                            @(Html.Kendo().DatePicker().Name("EndDate").Format("MMM dd,yyyy").Min(DateTime.Now).HtmlAttributes(new { style = "width: 70%" }))
                                            <span class="field-validation-valid text-danger" data-valmsg-for="EndDate" data-valmsg-replace="true"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Reason, htmlAttributes: new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                        <div class="col-lg-4 col-md-4 col-sm-5 col-xs-7">
                                            <textarea class="form-control k-textbox" cols="65" id="Reason" name="Reason" rows="5"
                                                      data-val-length-max="500" data-val-length="Reason cannot be longer than 500 characters."></textarea>
                                            <span class="field-validation-valid text-danger" data-valmsg-for="Reason" data-valmsg-replace="true"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10 col-sm-offset-3 col-sm-9 col-xs-12">
                                            <input type="button" value="Request" class="btn green" id="btn_leave_App_Save" data-toggle="tooltip" title="Request For Leave" data-placement="bottom" data-container="body"/>
                                            <input type="button" value="Refresh" class="btn yellow" id="btn_leave_App_Refresh" data-toggle="tooltip" title="Reset Application Form" data-placement="bottom" data-container="body"/>
                                            <input type="button" value="Cancel" class="btn red" id="btn_leave_App_Cancel" data-toggle="tooltip" title="Cancel Application" data-placement="bottom" data-container="body"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}
<script>
    $("input[data-val-date]").removeAttr("data-val-date");
    $(document).ready(function () {
        $("#liForHR").addClass('active');
        $("#StartDate").val("");
        $("#EndDate").val("");
    });
    
    $('#btn_leave_App_Cancel').click(function () {
        window.history.back();
    });
    $('#btn_leave_App_Refresh').click(function () {
        location.reload();
    });
    $("#btn_leave_App_Save").click(function () {
        var validatable = $("#div_Leave_App").kendoValidator({
            rules: {
                Reason: function (input) {
                    if (input.is("[name=Reason]") && $("#Reason").val() === '') {
                        return false;
                    }
                    return true;
                },
                dateValidate: function (input) {
                    if (input.is("[name=DateValidation]")) {
                        var StartDate = $("#StartDate").val();
                        var EndDate = $("#EndDate").val();
                        if (new Date(StartDate) > new Date(EndDate)) {
                            return false;
                        }
                        else {
                            return true;
                        }
                    }
                    return true;
                }
            },
            messages: {
                Reason: "Please enter reason",
                dateValidate:"Start date can not be greater than end date"
            }
        }).data("kendoValidator");
        if (validatable.validate()) {
            notification.show({ message: "Date is saving...", showTime: startTime() }, "upload-progress");
            var sendData = {
                ApplicationUserId: '@(Model.ApplicationUserId)',
                StartDate: $("#StartDate").val(),
                EndDate: $("#EndDate").val(),
                ApproveStatus: 0,
                Reason: $("#Reason").val(),
                userId: userId
            };
            $.ajax({
                url: '@Url.Action("LeaveAppRequestSave", "LeaveManagement")',
                type: 'Post',
                data: sendData,
                success: function (data) {
                    notification.hide();
                    notification.setOptions({autoHideAfter: 5000});
                    if (data != null) {
                        if (data === 'Success') {
                            notification.show({ message: "Leave appliation has been successfully saved.", showTime: startTime() }, "upload-success");
                            location.reload();
                        }
                        else {
                            notification.show({ message: "Leave appliation save was unsuccessful.", showTime: startTime() }, "upload-error");
                        }
                    }
                },
                error: function (error) {
                    notification.hide();notification.setOptions({autoHideAfter: 5000});
                    notification.show({ message: "Unsuccessful", showTime: startTime() }, "upload-error");
                }
            });
        }
    });
</script>

FactoryManagement/Views/LeaveManagement/ShowAllRequestedLeaveApplication.cshtml
@************************************** Created By Jerin Jahan (Date:12.01.2017) ********************************************************@

@{
    ViewBag.Title = "User Lists";
    Layout = "~/Views/Shared/_LayoutForTemplate.cshtml";
    FactoryManagement.Models.FactoryManagementEntities db = new FactoryManagement.Models.FactoryManagementEntities();
}
<div class="row">
    @*<p><a href="/HumanResource/AddEmployee"><span class="btn btn-success"><i class="fa fa-plus"></i> Add New User</span></a></p>*@
    <div id="div_User_List">
        <div id="Div_All_Requested_Leave_App" style="display:none;"><div class="loading_partial"></div></div>
        @if (db.View_UserLists.Where(m => m.Status == 1).Any())
        {
            <script>
                $("#Div_All_Requested_Leave_App").show();
                $("#Div_All_Requested_Leave_App").append('<div class="loading_partial"></div>');
                $("#Div_All_Requested_Leave_App").load('@Url.Action("_ShowAllRequestedLeave", "LeaveManagement")');
            </script>
        }
    </div>
</div>
<div id="win_leave_edit"></div>

<script id="temp_win_alert" type="text/x-kendo-template">
    <div style="padding:1em;">
        <p style="font-size: 14px; padding: 10px">#=message#</p>
        <div style="text-align: right;">
            <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="btn_temp_alert_ok"><span class="k-icon k-update"></span>OK</button>
            <button type="button" class="k-button k-button-icontext k-grid-cancel" id="btn_temp_alert_cancel"><span class="k-icon k-cancel"></span>Cancel</button>
        </div>
    </div>
</script>

<script>
    $(document).ready(function () {
        $("#liForHR").addClass('active');
        $("#liForUserLists").addClass('sublistActive');
        $("#liForHR").addClass('active');
        $("#liForUserLists").addClass('sublistActive');
        $("#top_header_link").append('<span>HR</span>' +
            '<span><i class="fa fa-angle-right fa-2x"></i></span>' +
            '<span>Leave Management</span>' +
            '<span><i class="fa fa-angle-right fa-2x"></i></span>' +
            '<span class="current"><a href="/LeaveManagement/ShowAllRequestedLeaveApplication"> Requested Leave Aplication</a></span>');
    });


    //************************** Approve Application **********************************************
    $("#Div_All_Requested_Leave_App").on("click", ".btn_approve_leave", function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var kendoWindow = $("<div/>").kendoWindow({
            actions: ["Close"],
            title: "Alert",
            resizable: false,
            width: "30%",
            modal: true
        });
        message = "Are you sure you want to approve this request?";
        var template = kendo.template($("#temp_win_alert").html());
        kendoWindow.data("kendoWindow").content(template).center().open();
        kendoWindow.find("#btn_temp_alert_cancel").click(function () {
            kendoWindow.data("kendoWindow").close();
        }).end();
        kendoWindow.find("#btn_temp_alert_ok").click(function () {
            kendoWindow.data("kendoWindow").close();
            approveApp(id);
        }).end();
    });
    function approveApp(id) {
        notification.show({ message: "Application is approving...", showTime: startTime() }, "upload-progress");
        $.ajax({
            url: '@Url.Action("LeaveAppApprove", "LeaveManagement")',
            type: 'Post',
            data: { id: id, userId: userId },
            success: function (data) {
                notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                if (data === "Error") {
                    notification.show({ message: "Application rejection was unsuccessful.", showTime: startTime() }, "upload-error");
                }
                else {
                    notification.show({ message: "Application has been successfully rejected.", showTime: startTime() }, "upload-success");

                    $("#Div_All_Requested_Leave_App").empty();
                    $("#Div_All_Requested_Leave_App").append('<div class="loading_partial"></div>');
                    $("#Div_All_Requested_Leave_App").load('@Url.Action("_ShowAllRequestedLeave", "LeaveManagement")');
                }
            }
        });
    }


    //************************** Reject Application **********************************************
    $("#Div_All_Requested_Leave_App").on("click", ".btn_reject_leave", function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var kendoWindow = $("<div/>").kendoWindow({
            actions: ["Close"],
            title: "Alert",
            resizable: false,
            width: "30%",
            modal: true
        });
        message = "Are you sure you want to reject this request?";
        var template = kendo.template($("#temp_win_alert").html());
        kendoWindow.data("kendoWindow").content(template).center().open();
        kendoWindow.find("#btn_temp_alert_cancel").click(function () {
            kendoWindow.data("kendoWindow").close();
        }).end();
        kendoWindow.find("#btn_temp_alert_ok").click(function () {
            kendoWindow.data("kendoWindow").close();
            rejectApp(id);
        }).end();
    });
    function rejectApp(id) {
        notification.show({ message: "Application is rejecting...", showTime: startTime() }, "upload-progress");
        $.ajax({
            url: '@Url.Action("LeaveAppReject", "LeaveManagement")',
            type: 'Post',
            data: { id: id, userId: userId },
            success: function (data) {
                notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                if (data === "Error") {
                    notification.show({ message: "Application rejection was unsuccessful.", showTime: startTime() }, "upload-error");
                }
                else {
                    notification.show({ message: "Application has been successfully rejected.", showTime: startTime() }, "upload-success");

                    $("#Div_All_Requested_Leave_App").empty();
                    $("#Div_All_Requested_Leave_App").append('<div class="loading_partial"></div>');
                    $("#Div_All_Requested_Leave_App").load('@Url.Action("_ShowAllRequestedLeave", "LeaveManagement")');
                }
            }
        });
    };



    //************************** Edit Application **********************************************
    $("#Div_All_Requested_Leave_App").on("click", ".btn_edit_leave", function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var kendoWindow = $("<div/>").kendoWindow({
            actions: ["Close"],
            title: "Alert",
            resizable: false,
            width: "30%",
            modal: true
        });
        message = "Are you sure you want to edit this application?";
        var template = kendo.template($("#temp_win_alert").html());
        kendoWindow.data("kendoWindow").content(template).center().open();
        kendoWindow.find("#btn_temp_alert_cancel").click(function () {
            kendoWindow.data("kendoWindow").close();
        }).end();
        kendoWindow.find("#btn_temp_alert_ok").click(function () {
            EditApp(id);
            kendoWindow.data("kendoWindow").close();
        }).end();
    });
    function EditApp(id) {
        $("#win_leave_edit").empty();
        $("#win_leave_edit").kendoWindow({
            actions: ["Close"],
            draggable: false,
            modal: true,
            visible: false,
            width: '60%',
            position: { top: '20%' },
            title: 'Edit Leave Application'
        });
        $("#win_leave_edit").html('<div class="loading_half"></div>');
        var win_leave_edit = $("#win_leave_edit").data("kendoWindow");
        win_leave_edit.refresh({ url: "/LeaveManagement/_LeaveAppEdit?id=" + id });
        win_leave_edit.center().open();
    }

    function onAdditionalData() {
        return { prefix: $("#ApplicationUser").val() };
    }
    function UserNameSelect(e) {
        var dataItem = this.dataItem(e.item.index());
        App_userId = dataItem.UserId
    }

</script>

FactoryManagement/Views/LeaveManagement/_LeaveAppEdit.cshtml
@************************************** Created By Jerin Jahan (Date:13.01.2017)  ***************************************@
@{
    DateTime now = DateTime.Now;
}

<div class="k-edit-form-container col-lg-11 col-md-10 col-sm-11 col-xs-10" style="margin-bottom:4%;width:96%!important;">
    <div id="div_leave_edit_partial"><div class="win_loading_half"></div></div>
    <script>
        var sendData = { id: '@(ViewBag.id)',v:"p"};
        $("#div_leave_edit_partial").load('@Url.Action("LeaveApplication", "LeaveManagement")', sendData);
    </script>
  
    <div class="k-edit-buttons k-state-default col-xs-11">
        <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="btn_leave_edit_save">
            <span class="k-icon k-update"></span>Update
        </button>
        <button type="reset" class="k-button k-button-icontext k-grid-cancel" id="btn_leave_edit_Refresh">
            <span class="k-icon k-i-refresh"></span>Refresh
        </button>
        <button type="reset" class="k-button k-button-icontext k-grid-cancel" id="btn_leave_edit_Cancle">
            <span class="k-icon k-cancel"></span>Cancel
        </button>
    </div>
</div>

FactoryManagement/Views/LeaveManagement/_LeaveRejectReason.cshtml
@********************* Created By Jerin Jahan (Date:16.01.2017) *******************************@

<div class="k-edit-form-container col-lg-11 col-md-10 col-sm-11 col-xs-10" style="margin-bottom:4%;width:96%!important;" id="Div_Reject_Reason">
    <div class=" editor-label"><label for="Reason">Reason</label></div>
    <div class="editor-field">
        <textarea class="form-control k-textbox" cols="65" id="Reason" name="Reason" rows="5" 
                  data-val-length-max="500" data-val-length="Reason cannot be longer than 500 characters."></textarea>
        <span class="field-validation-valid text-danger" data-valmsg-for="Reason" data-valmsg-replace="true"></span>
    </div>
    <div class="k-edit-buttons k-state-default">
        <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="btn_temp_reject"><span class="k-icon k-update"></span>Confirm</button>
        <button type="button" class="k-button k-button-icontext k-grid-cancel" id="btn_temp_reject_cancel"><span class="k-icon k-cancel"></span>Cancel</button>
    </div>
</div>
<script>
    $("#btn_temp_reject_cancel").click(function () {
        $(this).closest(".k-window-content").data("kendoWindow").close();
    });
    $("#btn_temp_reject").click(function () {
        var validation = $("#Div_Reject_Reason").kendoValidator({
            rules: {
                reason: function (input) {
                    if (input.attr('name') === "Reason" && $("#Reason").val() === '') {
                        return false;
                    }
                    return true;
                }
            },
            messages: {
                reason:"Please enter reject reason",
            }
        }).data("kendoValidator");

        if (validation.validate()) {
            notification.show({ message: "Application is rejecting...", showTime: startTime() }, "upload-progress");
            $.ajax({
                url: '@Url.Action("LeaveAppReject", "LeaveManagement")',
                type: 'Post',
                data: { id: '@(ViewBag.id)', userId: userId, Reason: $("#Reason").val() },
                success: function (data) {
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    if (data === "Error") {
                        notification.show({ message: "Application rejection was unsuccessful.", showTime: startTime() }, "upload-error");
                    }
                    else {
                        $("#btn_temp_reject").closest(".k-window-content").data("kendoWindow").close();
                        notification.show({ message: "Application has been successfully rejected.", showTime: startTime() }, "upload-success");

                        $("#div_For_Partial").empty();
                        $("#div_For_Partial").append('<div class="loading_partial"></div>');
                        $("#div_For_Partial").load(url);
                    }
                },
                error: function (er) {
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    notification.show({ message: "Error occurred.", showTime: startTime() }, "upload-warning");
                }
            });
        }
    });
</script>