FactoryManagement/Controllers/HumanResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using FactoryManagement.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System.Xml;
using Newtonsoft.Json;
using System.Collections;
using System.Data.SqlClient;
using System.IO;
using System.Web.Script.Serialization;
using FactoryManagement.ModelView;
using FactoryManagement.ModelView.HR;
using System.Web.Helpers;
using FactoryManagement.ModelView.SalaryConfig;
using System.ComponentModel;
using System.Configuration;
using FactoryManagement.Filters;

namespace FactoryManagement.Controllers
{
    [Authorize]
    [DisplayName("Human Resource")]
    public class HumanResourceController : Controller
    {
        #region Private Properties
        private FactoryManagementEntities db = new FactoryManagementEntities();
        static private int offset = Convert.ToInt32(ConfigurationManager.AppSettings["localTime"]);
        DateTime now = DateTime.UtcNow.AddMinutes(offset);
        const int ShowUserPerPage = 20;
        const int ShowPaidHisPage = 20;
        const int ShowTranPage = 20;
        const int ShowRevertedPerPage = 20;
        const int ShowUserLoanPerPage = 20;
        const int MonthSalUser = 20;
        #endregion

        #region User Create,Edit,Delete
        public ActionResult AddEmployee()
        {
            UserInformationModelView model = new UserInformationModelView();
            ViewBag.DesignationId = new SelectList(db.Designations, "DesignationId", "DesignationName");
            ViewBag.Religion = new SelectList(db.ReligionLists, "ReligionId", "Religion");
            ViewBag.DivisionList = new SelectList(db.DivisionLists, "DivisionId", "DivisionName");
            var SiteList = (from m in db.SiteLists
                            where m.IsResidential == false && m.Status == 1
                            select new
                            {
                                Id = m.Id,
                                SiteName = m.SiteName,
                                IsComposite = m.IsComposite
                            }).ToList();
            ViewBag.SiteId = SiteList;
            ViewBag.CountryId = new SelectList(db.CountryLists, "CountryCode", "CountryName");
            ViewBag.TitleId = new SelectList(db.NameTitles, "Id", "Name");
            return View(model);
        }
        public JsonResult AddEmployeeInfo(UserInformationModelView model, IEnumerable<HttpPostedFileBase> files)
        {
            string msg = "";
            string name = "";
            int ColumnId = 0;
            int OperationStatus = 1;
            string fullName = "";
            string NtlId_FrntImg = "";
            string NtlId_BckImg = "";
            string Paths = Server.MapPath("~/Images/UserPicture/");

            if (!Directory.Exists(Paths))
            {
                Directory.CreateDirectory(Paths);
            }
            UserInformation user = new UserInformation();
            user.Title = model.Title;
            user.FirstName = model.FirstName;
            user.MiddleName = model.MiddleName;
            user.LastName = model.LastName;
            user.UserType = model.UserType;
            user.DateOfBirth = Convert.ToDateTime(model.DateOfBirth);
            user.DesignationId = model.DesignationId;
            user.Gender = model.Gender;
            user.Nationality = model.Nationality;
            user.NationalId = model.NationalId;
            user.Phone = model.Phone;
            user.Gender = model.Gender;
            user.Religion = model.Religion;
            user.BasicSalary = model.BasicSalary;
            user.EmailAddress = model.EmailAddress;
            user.MobileNo = model.MobileNo;
            user.ParAddress = model.ParAddress;
            user.ParAddressLine1 = model.ParAddressLine1;
            user.ParCountry = model.ParCountry;
            user.ParDivisionId = model.ParDivisionId;
            user.ParCity = model.ParCity;
            user.ParArea = model.ParArea;
            user.ParState = model.ParState;
            user.ParPotalCode = model.ParPotalCode;
            user.PictureOriginalName = model.PictureOriginalName;
            user.SiteId = model.SiteId;
            user.CreatedBy = model.CreatedBy;
            user.CreatedDate = now;
            user.JoinDate = model.JoinDate;
            user.Status = 0;
            user.EmpId = model.EmpId;
            user.DeptId = model.DeptId;
            user.SiteId = model.SiteId;
            user.LineId = model.LineId;
            user.UnitId = model.UnitId;
            user.MachineId = model.MachineId;
            user.AssginSalary = false;
            if (model.SamePresentAddress == true)
            {
                user.PreAddress = model.ParAddress;
                user.PreAddressLine1 = model.ParAddressLine1;
                user.PreCountry = model.ParCountry;
                user.PreDivisionId = model.ParDivisionId;
                user.PreCity = model.ParCity;
                user.PrePostalCode = model.ParPotalCode;
                user.PreArea = model.ParArea;
                user.PreState = model.ParState;
                user.SamePresentAddress = true;
            }
            else
            {
                user.PreAddress = model.PreAddress;
                user.PreAddressLine1 = model.PreAddressLine1;
                user.PreCountry = model.PreCountry;
                user.PreState = model.PreState;
                user.PreDivisionId = model.PreDivisionId;
                user.PreCity = model.PreCity;
                user.PrePostalCode = model.PrePostalCode;
                user.PreArea = model.PreArea;
                user.SamePresentAddress = false;
            }

            try
            {
                db.UserInformations.Add(user);
                db.SaveChanges();
                OperationStatus = 1;

                name = user.FirstName + " " + model.MiddleName + " " + model.LastName;
                ColumnId = Convert.ToInt32(db.UserInformations.Where(m => m.CreatedBy == model.CreatedBy).Max(m => m.UserId));
                msg = "User" + " " + "'" + name + "'" + " " + "Created on " + now.ToString("MMM dd , yyy hh:mm tt");
            }
            catch (Exception)
            {
                msg = "User" + " " + "'" + name + "'" + " " + "Creation Failed on " + now.ToString("MMM dd , yyy hh:mm tt");
                OperationStatus = -1;
                // throw;
            }
            SaveAuditLog("Create New User", msg, "HR", "AddEmployee", "UserInformation", ColumnId, Convert.ToInt32(model.CreatedBy), now, OperationStatus);
            if (files != null)
            {
                int i = 0;
                UserInformation anuser = db.UserInformations.Find(user.UserId);
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        Random generator = new Random();
                        string random = generator.Next(0, 1000000).ToString("D6");
                        string s = file.FileName;
                        int idx = s.LastIndexOf('.');
                        string fileName = s.Substring(0, idx);
                        string extension = s.Substring(idx);
                        byte[] imageByte = null;
                        BinaryReader rdr = new BinaryReader(file.InputStream);
                        imageByte = rdr.ReadBytes((int)file.ContentLength);
                        anuser.ImageData = imageByte;
                        if (i == 0)
                        {
                            fullName = "Emp" + ColumnId + random + extension;
                            anuser.Picture = fullName;
                            Paths = Path.Combine(Server.MapPath("~/Images/UserPicture/Original"), fullName);
                            file.SaveAs(Paths);
                            WebImage imgForGallery = new WebImage(file.InputStream);
                            if (imgForGallery.Width > 70)
                            {
                                imgForGallery.Resize(29, 29, false, true);
                            }
                            string PathsResize = Path.Combine(Server.MapPath("~/Images/UserPicture/thumb"), fullName);
                            imgForGallery.Save(PathsResize);
                        }
                        else if (i == 1)
                        {
                            NtlId_FrntImg = "NtlId_FrntImg" + ColumnId + random + extension;
                            anuser.NationalIdFontImg = NtlId_FrntImg;

                            Paths = Path.Combine(Server.MapPath("~/Images/UserPicture/NationalId/Original"), NtlId_FrntImg);
                            file.SaveAs(Paths);
                            WebImage imgForGallery = new WebImage(file.InputStream);
                            if (imgForGallery.Width > 70)
                            {
                                imgForGallery.Resize(29, 29, false, true);
                            }
                            string PathsResize = Path.Combine(Server.MapPath("~/Images/UserPicture/NationalId/thumb"), NtlId_FrntImg);
                            imgForGallery.Save(PathsResize);
                        }
                        else
                        {
                            NtlId_BckImg = "NtlId_BckImg" + ColumnId + random + extension;
                            anuser.NationalIdBackImg = NtlId_BckImg;
                            Paths = Path.Combine(Server.MapPath("~/Images/UserPicture/NationalId/Original"), NtlId_BckImg);
                            file.SaveAs(Paths);
                            WebImage imgForGallery = new WebImage(file.InputStream);
                            if (imgForGallery.Width > 70)
                            {
                                imgForGallery.Resize(29, 29, false, true);
                            }

FactoryManagement/Views/HumanResource/EmployeeBasicDetails_left.cshtml
@{ 
    FactoryManagement.Models.FactoryManagementEntities db = new FactoryManagement.Models.FactoryManagementEntities();
    long id = ViewBag.UserId;
    var user = db.View_UserLists.Where(x => x.UserId ==id ).FirstOrDefault();
}
<img src="~/Images/UserPicture/Original/@user.Picture"/>

FactoryManagement/Views/HumanResource/_AddNewBankAc.cshtml
@model FactoryManagement.ModelView.HR.User_Bank_Account_ModelView
<div class="k-edit-form-container col-lg-11 col-md-10 col-sm-11 col-xs-10" style="margin-bottom:4%;margin-top:2%;" id="div_for_bankAc_Validation">
    @Html.HiddenFor(model => model.BankId)
    <div class="editor-label"><label for="BankName">Bank Name</label></div>
    <div class="editor-field">
        @Html.EditorFor(model => model.BankName, new { htmlAttributes = new { @class = "form-control k-textbox" } })
        @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
    </div>
    <div class="editor-label"><label for="BranchName">Branch Name</label></div>
    <div class="editor-field">
        @Html.EditorFor(model => model.BranchName, new { htmlAttributes = new { @class = "form-control k-textbox" } })
        @Html.ValidationMessageFor(model => model.BranchName, "", new { @class = "text-danger" })
    </div>
    <div class="editor-label"><label for="AccountNumber">A/C No.</label></div>
    <div class="editor-field">
        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control k-textbox" } })
        @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
    </div>
    <div class="editor-label">@Html.HiddenFor(model => model.IsPrimary) </label></div>
    <div class="editor-field">
        <input type="checkbox" id="IsPrimaryAc" value="Primary">
        <span> Is Primary A/C</span>
    </div>
    <div class="col-sm-11 col-xs-11" style="margin-top:5px;float:right">
        <div class="k-edit-buttons k-state-default">
            @if (Model.BankId == 0)
            {  <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="bankac_add_edit_create"><span class="k-icon k-update"> </span>Create</button>}
            else
            {<button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="bankac_add_edit_update"><span class="k-icon k-update"> </span>Update</button>}
            <button type="button" class="k-button k-button-icontext k-grid-cancel" id="bankac_add_edit_refresh"><span class="k-icon k-i-refresh"></span>Refresh</button>
            <button type="button" class="k-button k-button-icontext k-grid-cancel" id="bankac_add_edit_cancel"><span class="k-icon k-cancel"></span>Cancel</button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var addorEdit = $("#BankId").val();
        $("#IsPrimaryAc").prop('checked', false);
        if (addorEdit > 0) {
            var checkbox = $("#IsPrimary").val();
            if (checkbox=='True') {
                $("#IsPrimaryAc").prop('checked', true);
            }
        }
    });
    $("#bankac_add_edit_refresh").click(function () {
        $("#Div_For_bankac_add").empty();
        $("Div_For_bankac_add").append('<div class="partial_loading_half"></div>');
        var data={
            UserId:EmpId,
            BankId:bankId
        }
        $("#Div_For_bankac_add").load('@Url.Action("AddNewBankAc", "HumanResource")', data);
    });
    $("#bankac_add_edit_cancel").click(function (e) {
        
        $(this).closest(".k-window-content").data("kendoWindow").close();

    });
    $("#bankac_add_edit_update").click(function () {
     
        var valid = checkValidation(EmpId);
        if (valid) {
            if (hasPreviousPrimary == 'True' && $("#IsPrimaryAc").is(":checked")) {
                var kendoWindow = $("<div />").kendoWindow({
                    actions: ["Close"],
                    title: "Alert",
                    resizable: false,
                    width: "30%",
                    modal: true
                });
                msg = "You have already a bank account as primary.Do you still want to set this account as primary ?";
                var template = kendo.template($("#temp_confirmation_dialog").html());
                kendoWindow.data("kendoWindow").content(template).center().open();

                kendoWindow.find("#btn_confirm_cancel").click(function () {
                    kendoWindow.data("kendoWindow").close();
                    return;
                }).end();
                kendoWindow.find("#btn_confirm_ok").click(function () {
                    var sendData = {
                        BankId: $("#BankId").val(),
                        BankName: $("#BankName").val(),
                        BranchName: $("#BranchName").val(),
                        AccountNumber: $("#AccountNumber").val(),
                        CreatedBy: userId,
                        UserId:EmpId,
                        IsPrimary: $("#IsPrimaryAc").is(":checked")
                    };
                    updateBank(sendData);
                    kendoWindow.data("kendoWindow").close();
                }).end();
            } else {
                primaryBankId = 0;
                var sendData = {
                    BankId: $("#BankId").val(),
                    BankName: $("#BankName").val(),
                    BranchName: $("#BranchName").val(),
                    AccountNumber: $("#AccountNumber").val(),
                    CreatedBy: userId,
                    UserId: EmpId,
                    IsPrimary: $("#IsPrimaryAc").is(":checked")
                };
                updateBank(sendData);
            }
        }
    });
    function updateBank(sendData){
        $.ajax({
            url: '@Url.Action("UpdateBankAcofUser", "HumanResource")',
            type: 'Post',
            data: { bankInfo: sendData, primary: primaryBankId },
            success: function (data) {
                if (data == "Success") {
                    $("#bankac_add_edit_update").closest(".k-window-content").data("kendoWindow").close();
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    notification.show({ message: "Bank information '" + sendData .BankName+ "' has been successfully updated", showTime: startTime() }, "upload-success");
                    var data = { userId: EmpId };
                    $("#tab4BankAcList").load('@Url.Action("_UserBankAcDetails", "HumanResource")', data);
                }
                if (data == "Error") {
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    notification.show({ message: "Bank information '" + sendData.BankName + "' update was unsuccessful ", showTime: startTime() }, "upload-error");
                }
            },
            error: function (err) {
                notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                notification.show({ message: "Error occurred", showTime: startTime() }, "upload-warning");
            }
        });

    }
    $("#bankac_add_edit_create").click(function () {
        var valid = checkValidation(null);
        if (valid) {
            if (hasPreviousPrimary == 'True' && $("#IsPrimaryAc").is(":checked")) {
                var kendoWindow = $("<div />").kendoWindow({
                    actions: ["Close"],
                    title: "Alert",
                    resizable: false,
                    width: "30%",
                    modal: true
                });
                msg = "You have already a bank account as primary.Do you still want to set this account as primary ?";
                var template = kendo.template($("#temp_confirmation_dialog").html());
                kendoWindow.data("kendoWindow").content(template).center().open();

                kendoWindow.find("#btn_confirm_cancel").click(function () {
                    kendoWindow.data("kendoWindow").close();
                    return;
                }).end();
                kendoWindow.find("#btn_confirm_ok").click(function () {
                    var sendData = {
                        BankId: $("#BankId").val(),
                        BankName: $("#BankName").val(),
                        BranchName: $("#BranchName").val(),
                        AccountNumber: $("#AccountNumber").val(),
                        CreatedBy: userId,
                        UserId: EmpId,
                        IsPrimary: $("#IsPrimaryAc").is(":checked")
                    };
                    createBank(sendData);
                    kendoWindow.data("kendoWindow").close();
                }).end();
            } else {
                primaryBankId = 0;
                var sendData = {
                    BankId: $("#BankId").val(),
                    BankName: $("#BankName").val(),
                    BranchName: $("#BranchName").val(),
                    AccountNumber: $("#AccountNumber").val(),
                    CreatedBy: userId,
                    UserId: EmpId,
                    IsPrimary: $("#IsPrimaryAc").is(":checked")
                };
                createBank(sendData);
            }
        }
    });
    function createBank(sendData) {
        $.ajax({
            url: '@Url.Action("AddBankActoUser", "HumanResource")',
            type: 'Post',
            data: { bankInfo: sendData, primary: primaryBankId },
            success: function (data) {
                if (data == "Success") {
                    $("#bankac_add_edit_create").closest(".k-window-content").data("kendoWindow").close();
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    notification.show({ message: "Bank information '" + sendData.BankName + "' has been successfully saved.", showTime: startTime() }, "upload-success");
                    var data = { userId: EmpId };
                    $("#tab4BankAcList").load('@Url.Action("_UserBankAcDetails", "HumanResource")', data);
                }
                if (data == "Error") {
                    notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                    notification.show({ message: "Bank information '" + sendData.BankName+ "' saving was unsuccessful.", showTime: startTime() }, "upload-error");
                }
            },
            error: function (err) {
                notification.hide(); notification.setOptions({ autoHideAfter: 5000 });
                notification.show({ message: "Error occurred", showTime: startTime() }, "upload-warning");
            }
        });
    }
</script>

FactoryManagement/Views/HumanResource/_ChangeWorkingSchedule.cshtml
<div class="editor-label"><label>Working Schedule</label></div>
<div class="editor-field">
    @(Html.Kendo().DropDownList().Name("Working_ScheduleId")
                     .OptionLabel("--Select One Package--")
                     .BindTo(ViewBag.WorkingSchedules as SelectList)
                     .Events(e => e.Change("workingScheduleChange"))
                     .HtmlAttributes(new { style = "width:100%" })
    )
    <span class="field-validation-valid text-danger" data-valmsg-for="Working_ScheduleId" data-valmsg-replace="true"></span>
</div>
<div id="div_selected_work_scdl"></div>
<script>
    $(document).ready(function () {
        $("#div_selected_work_scdl").load('@Url.Action("SelectedSchedule","HumanResource")?id=' + '@(ViewBag.id)' + '&view=win');
    });
</script>

FactoryManagement/Views/HumanResource/_PaySalaryAllUser.cshtml
@************************************** Created By Jerin Jahan (Date:05.11.2016)  ***************************************@

<div class="k-edit-form-container col-lg-11 col-md-10 col-sm-11 col-xs-10" style="margin-bottom:4%;margin-top:2%;" >
    <div class="col-sm-12" style="float:left;" id="div_PaySalary_All"><div class="loading_partial"></div></div>
    <script>
        if ('@(ViewBag.PayType)' === 'Due') {
            var sendData = { userIds: allChkUserId, userType: allUserType };
            $("#div_PaySalary_All").load('@Url.Action("_ShowAllUserForDuePay", "HumanResource")', sendData);
        } else {
            var sendData = { userIds: allChkUserId, userType: allUserType };
            $("#div_PaySalary_All").load('@Url.Action("_ShowAllUserForSalaryPay", "HumanResource")', sendData);
        }
        
    </script>    
    <div class="k-edit-buttons k-state-default col-xs-11">
        <button type="reset" class="k-button k-button-icontext k-primary k-grid-update" id="btn_All_PayCancle">
            <span class="k-icon k-update"></span> OK
        </button>
    </div>
</div>
<script>
    var windowHeight = $(window).height() - $(".navbar-fixed-top").height() - $(".navbar-fixed-top").height();
    $("#div_Salary_pay_option").css('min-height', windowHeight);
    $("#btn_All_PayCancle").click(function () {
        $(this).closest(".k-window-content").data("kendoWindow").close();
    });
    $("#div_PaySalary_All").on("change", ".txt_AllUser_Pay", function (e) {
        if (parseFloat($(this).val()) > parseFloat($(this).data('maxamnt'))) {
            alert('Amount can not greater than total amount.');
            $(this).val($(this).data('maxamnt'));
        }
    });

    //****************************** All User Salary Pay ******************************************************
    $("#div_PaySalary_All").on("click", ".paySalary", function (e) {
        var validation = $("#div_PaySalary_All").kendoValidator({
            rules: {
                option: function (input) {
                    if (input.attr('name') === "AccPayTyp" && $("#SalaryPayType").val() === '0') {
                        return false;
                    }
                    return true;
                },
                Internal: function (input) {
                    if (input.attr('name') === 'InernalAccId' && $("#Cash").is(":checked") && $("#InernalAccId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankName: function (input) {
                    if (input.attr('name') === 'BankId' && $("#Check").is(":checked") && $("#BankId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankAccId: function (input) {
                    if (input.attr('name') === 'BankAccId' && $("#Check").is(":checked") && $("#BankAccId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankAccSlipNo: function (input) {
                    if (input.attr('name') === 'BankAccSlipNo' && $("#Check").is(":checked") && $("#BankAccSlipNo").val() === '') {
                        return false;
                    }
                    return true;
                },
            },
            messages: {
                option: "Please select one",
                Internal: "Please select one",
                BankName: "Please select one",
                BankAccId: "Please select one",
                BankAccSlipNo: "Please enter slip number"
            }
        }).data("kendoValidator");
        if (validation.validate()) {
            var Id = $(this).data('userid');
            var Type = $(this).data('usertype');
            var sendData = {
                EmpSalaryPayId: $(this).data('pckid'),
                UserId: $(this).data('userid'),
                UserType: $(this).data('usertype'),
                PayType: $("#SalaryPayType").val(),
                Amount: $("#Amount_" + Id + Type).val(),
                InernalAccId: internal_AccId,
                BankId: bankId,
                BankAccId: banlAccId,
                BankAccSlipNo: $("#BankAccSlipNo").val(),
                InsertBy: userId,
                username: $(this).data('username'),
                currency: Currency
            };

            $.ajax({
                url: '@Url.Action("SaveSingleUserSalary", "HumanResource")',
                type: 'Post',
                data: sendData,
                success: function (data) {
                    if (data !== "Error") {
                        if (data) {
                            $('#Amount_' + sendData.UserId + sendData.UserType).hide();
                            $('#PaidSalary_' + sendData.UserId + sendData.UserType).show();
                        } else {
                            alert('not payment');
                        }
                    }
                },
                error: function (xhr) {
                    alert('error');
                }
            });
        }
    });



    //****************************** All User Due Pay ******************************************************
    $("#div_PaySalary_All").on("click", ".DueSalary", function (e) {
        var Id = $(this).data('userid');
        var Type = $(this).data('usertype');
        var type_amnt = $("#Amount_" + Id + Type).val();
        var validation = $("#div_PaySalary_All").kendoValidator({
            rules: {
                option: function (input) {
                    if (input.attr('name') === "AccPayTyp" && $("#SalaryPayType").val() === '0') {
                        return false;
                    }
                    return true;
                },
                Internal: function (input) {
                    if (input.attr('name') === 'InernalAccId' && $("#Cash").is(":checked") && $("#InernalAccId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankName: function (input) {
                    if (input.attr('name') === 'BankId' && $("#Check").is(":checked") && $("#BankId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankAccId: function (input) {
                    if (input.attr('name') === 'BankAccId' && $("#Check").is(":checked") && $("#BankAccId").val() === '') {
                        return false;
                    }
                    return true;
                },
                BankAccSlipNo: function (input) {
                    if (input.attr('name') === 'BankAccSlipNo' && $("#Check").is(":checked") && $("#BankAccSlipNo").val() === '') {
                        return false;
                    }
                    return true;
                },
            },
            messages: {
                option: "Please select one",
                Internal: "Please select one",
                BankName: "Please select one",
                BankAccId: "Please select one",
                BankAccSlipNo: "Please enter slip number"
            }
        }).data("kendoValidator");
        if (validation.validate()) {
            if (parseFloat(type_amnt) > parseFloat(highest_amnt)) {
                alert('Your selected account highest amount for per transaction is =' + highest_amnt + ' ' + Currency+'.Payment value can not be greater than ' + highest_amnt + ' ' + Currency+'.');
            }
            else {
                var sendData = {
                    UserId: Id,
                    UserType: Type,
                    PayType: $("#SalaryPayType").val(),
                    Amount: type_amnt,
                    InernalAccId: internal_AccId,
                    BankId: bankId,
                    BankAccId: banlAccId,
                    BankAccSlipNo: $("#BankAccSlipNo").val(),
                    InsertBy: userId,
                    username: $(this).data('username'),
                    currency: Currency
                };
                $.ajax({
                    url: '@Url.Action("PayAllUserDue", "HumanResource")',
                    type: 'Post',
                    data: sendData,
                    success: function (data) {
                        if (data === "Success") {
                            $('#Amount_' + sendData.UserId + sendData.UserType).hide();
                            $('#DueSalary_' + sendData.UserId + sendData.UserType).hide();
                            $('#PaidDue_' + sendData.UserId + sendData.UserType).show();
                        } else {
                            alert(data);
                        }
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            }
            
        }
    });
</script>

FactoryManagement/Views/HumanResource/_UserDocumentTab.cshtml
<div class="col-sm-12" style="padding-left:0px!important;padding-right:0px!important;">
    <div class="panel with-nav-tabs panel-default">
        <div class="panel-heading">
            <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1doc" data-toggle="tab">Documents</a></li>
            </ul>
        </div>
        <div class="panel-body" style="border:none!important;">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1doc"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#tab1doc").append('<div class="loading_half"></div>');
        $("#tab1doc").load('@Url.Action("_UserDocuments", "HumanResource")?UserId=' + EmpId);
    });
</script>