FactoryManagement/Models/ProductTypeList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeList
    {
        public int ProductTypeId { get; set; }
        public string ProductTypeName { get; set; }
        public bool HasParent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool CanBeDeleted { get; set; }
    }
}

FactoryManagement/Controllers/SoldierController.cs
using FactoryManagement.Models;
using FactoryManagement.ModelView.Acquisition;
using FactoryManagement.ModelView.Auth;
using FactoryManagement.ModelView.Inventory;
using FactoryManagement.ModelView.Inventory.Mahinaries;
using FactoryManagement.ModelView.Inventory.Product;
using FactoryManagement.ModelView.Inventory.Store;
using FactoryManagement.ModelView.Inventory.Warehouse;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FactoryManagement.Controllers
{
    public class SoldierController : Controller
    {
        #region Private Properties
        private FactoryManagementEntities db = new FactoryManagementEntities();
        int ShowItemPerPage = 20;
        static private int offset = Convert.ToInt32(ConfigurationManager.AppSettings["localTime"]);
        DateTime now = DateTime.UtcNow.AddMinutes(offset);
        #endregion

        #region Create,Delete,Update and List of ProductType
        public ActionResult ProductTypeList()
        {
            return View();
        }
        public ActionResult _ShowAllProductTypeList()
        {
            var AllParentProductType = (from p in db.View_Categories
                                        where p.HasParent == false
                                        select new ProductTypeViewModel
                                        {
                                            ProductTypeId = p.CategoryId,
                                            ProductTypeName = p.CategoryName,
                                            CreatedBy = p.CreatedBy,
                                            CreatedDateName = p.CreatedDateName,
                                            HasChild = p.HasChild,
                                            UpdatedDate = p.UpdatedDate,
                                            UpdatedBy = p.UpdatedBy,
                                            UpdatedDateFormate = p.UpdatedDateFormate,
                                            CanBeDeleted = p.CanBeDeleted
                                        }).OrderBy(p => p.ProductTypeName).ToList();
            ViewBag.AllParentProType = AllParentProductType;
            return PartialView();
        }
        public JsonResult GetAllProductTypeForList(int? ParentId)
        {
            int id = Convert.ToInt32(ParentId);
            var list = (from m in db.View_Categories
                        where m.ParentId == id
                        select new
                        {
                            ProductTypeId = m.CategoryId,
                            ProductTypeName = m.CategoryName,
                            HasParent = m.HasParent,
                            ParentId = m.ParentId,
                            ParentName = m.ParentName,
                            CreatedBy = m.CreatedBy,
                            CreatedDateName = m.CreatedDateName,
                            HasChild = m.HasChild,
                            UpdatedDateFormate = m.UpdatedDateFormate,
                        }).OrderBy(p => p.ProductTypeName).ToList();

            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ProductTypeCreate(int? ProductTypeId, int? ParentId, string ParentName)
        {
            ProductTypeViewModel model = new ProductTypeViewModel();
            if (ParentId != null)
            {
                model.HasParent = true;
                model.ParentId = ParentId;
                model.ParentName = ParentName;
            }
            if (ProductTypeId != null)
            {
                View_Categories pro_type = db.View_Categories.Where(m => m.CategoryId == ProductTypeId).FirstOrDefault();
                model.ProductTypeId = pro_type.CategoryId;
                model.ProductTypeName = pro_type.CategoryName;
                model.HasParent = pro_type.HasParent;
                model.ParentId = pro_type.ParentId;
                model.ParentName = pro_type.ParentName;
                model.HasChild = pro_type.HasChild;
            }
            return PartialView(model);
        }
        public JsonResult ProductTypeCreateSave(Category model)
        {
            if (ModelState.IsValid)
            {
                int ColumnId = 0;
                int OperationStatus = 1;

                Category pro_type = new Category();
                if (model.CategoryId > 0)
                {
                    pro_type = db.Categories.Find(model.CategoryId);
                    pro_type.CategoryName = model.CategoryName;
                    pro_type.HasParent = model.HasParent;
                    pro_type.ParentId = model.ParentId;
                    pro_type.UpdatedBy = model.CreatedBy;
                    pro_type.UpdatedDate = now;
                    db.Entry(pro_type).State = EntityState.Modified;
                    ColumnId = pro_type.CategoryId;
                }
                else
                {
                    pro_type.CategoryName = model.CategoryName;
                    pro_type.HasParent = model.HasParent;
                    pro_type.ParentId = model.ParentId;
                    pro_type.CreatedBy = model.CreatedBy;
                    pro_type.CreatedDate = now;
                    pro_type.CanBeDeleted = true;
                    db.Categories.Add(pro_type);                   
                }
                try
                {
                    db.SaveChanges();
                    if (model.CategoryId == 0)
                    {
                        ColumnId = db.Categories.Max(m => m.CategoryId);
                    }
                }
                catch (Exception)
                {
                    OperationStatus = -1;
                }
                if (OperationStatus == 1)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Error", JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult ProductTypeDestroy(int? ProductTypeId, long UserId, string ParentName)
        {

            var allCat = db.Categories.ToList();
            foreach(var v in allCat)
            {
                db.Categories.Remove(v);
                db.SaveChanges();
            }
            var allPro = db.ProductItemLists.ToList();
            foreach(var p in allPro)
            {
                db.ProductItemLists.Remove(p);
                db.SaveChanges();
            }
            if (ProductTypeId != null)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

FactoryManagement/Views/Soldier/ProductTypeCreate.cshtml
@*----------------------Created By (Jerin Jahan) Date(22-03-2017)-----------------*@

@model FactoryManagement.ModelView.Inventory.Product.ProductTypeViewModel

@using (Html.BeginForm("ProductTypeCreateSave", "Inventory", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.ProductTypeId)
    @Html.HiddenFor(m => m.HasParent)
    @Html.HiddenFor(m => m.ParentId)
    @Html.HiddenFor(m => m.ParentName)
    @Html.HiddenFor(m => m.CreatedBy)

    <br />
    <div class="k-edit-form-container" id="divForProCreate">
        <div class="editor-label"><label>Product Type Name</label></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductTypeName, new { htmlattributes = new { @class = "k-textbox", @style = "width:100%" } })
            @Html.ValidationMessageFor(model => model.ProductTypeName, "", new { @class = "text-Danger" })
        </div>

        <div class="k-edit-buttons k-state-default">
            @if (Model.ProductTypeId != 0)
            {
                <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="btnCreate"><span class="k-icon k-update"></span>Update</button>
            }
            else
            {
                <button type="button" class="k-button k-button-icontext k-primary k-grid-update" id="btnCreate"><span class="k-icon k-update"></span>Create</button>
            }
            <button type="button" class="k-button k-button-icontext k-grid-cancel" id="btnCancel"><span class="k-icon k-cancel"></span>Cancel</button>
        </div>
    </div>
    <br />
}
<script>
    var validation = $("#divForProCreate").kendoValidator().data("kendoValidator");
    $("#btnCreate").click(function () {
        var msg = "";
        if (validation.validate()) {
            var sendData = {
                CategoryId: $("#ProductTypeId").val(), CategoryName: $("#ProductTypeName").val(),
                HasParent: $("#HasParent").val(), ParentId: $("#ParentId").val(), ParentName: $("#ParentName").val(), CreatedBy: userId
            };
            msg = ($("#ProductTypeId").val() > 0) ? "Updating product type information" : "Creating new product Type";
            notification.show({
                message: msg,showTime: startTime()}, "upload-progress");
            $.ajax({
                url: '@Url.Action("ProductTypeCreateSave", "Soldier")',
                type: 'Post',
                data: sendData,
                success: function (response) {
                    $("#window").data("kendoWindow").close();
                    notification.hide(); notification.setOptions({ autoHideAfter: 2000 });
                    if (response === "Success") {
                        if ($("#ProductTypeId").val() > 0) {
                            msg = "Product type information successfully updated";
                        } else {
                            msg = ($("#HasParent").val() == 'True') ? "Product type successfully added" : "Product type successfully created";
                        }
                        notification.show({message: msg, showTime: startTime()}, "upload-success");
                        $("#divForAll_Pro_type").empty();
                        $("#divForAll_Pro_type").append('<div class="loading_partial"></div>');
                        $("#divForAll_Pro_type").load('@Url.Action("_ShowAllProductTypeList", "Soldier")');
                    }
                    else {
                        msg = ($("#HasParent").val() == 'True') ? "Add product type attempt unsuccessful" : "Product type create attempt unsuccessful";
                        notification.show({message: msg, showTime: startTime()}, "upload-error");
                    }
                }
            });
        }
    });
    $("#btnCancel").click(function () {
        $(this).closest(".k-window-content").data("kendoWindow").close();
    });
</script>

FactoryManagement/Views/Soldier/ProductTypeList.cshtml
@************************************** Created By Mabia Mishu (Date:01.09.2016)  ***************************************@

@model IEnumerable<FactoryManagement.ModelView.Inventory.Product.ProductTypeViewModel>

@{
    ViewBag.Title = "All Product Type List";
    Layout = "~/Views/Shared/_LayoutForTemplate.cshtml";
}

<div class="row">
    <p><span class="btn btn-success" id="btn_protype_create"><i class="fa fa-plus"></i> Add New Product Type</span></p>
    <div id="divForAll_Pro_type">
        <div class="loading_partial"></div>
    </div>
</div>

@(Html.Kendo().Window()
           .Name("window")
           .Visible(false)
           .Modal(true)
           .Draggable(true)
)
<script>
    $(document).ready(function () {
        $("#divForAll_Pro_type").load('@Url.Action("_ShowAllProductTypeList", "Soldier")');
    });
    $("#divForAll_Pro_type").on("click", ".btn_expandProductType", function (e) {
        e.preventDefault();
        var typeId = $(this).data("id");
        $(this).find('i').toggleClass('fa-plus-square-o fa-2 fa-minus-square-o fa-2');
        if ($(this).data("isclick") == "0") {
            $(this).data("isclick", "1");
            $(this).attr("dataisclick", "1");
            $.ajax({
                url: '@Url.Action("GetAllProductTypeForList", "Soldier")',
                type: 'Post',
                data: { ParentId: typeId },
                success: function (data) {
                    if (data) {
                        $(".trforchild_" + typeId).empty();
                        $(".trforchild_" + typeId).show();
                        var crntSpan = $("#spanForName_" + typeId);
                        var getPadValue = parseInt(crntSpan.css('padding-left'));
                        for (var i in data) {
                            $('<tr id="tr_' + data[i].ProductTypeId + '" class="trforchild_' + typeId + '" data-proid="' + data[i].ProductTypeId + '" data-prochild="' + data[i].HasChild + '">' +
                                '<td><span id="spanForName_' + data[i].ProductTypeId + '">' +
                                ((data[i].HasChild == 'True') ? '<span class="btn_expandProductType" id="newtrForAp_' + data[i].ProductTypeId + '" data-id="' + data[i].ProductTypeId +
                                '" data-isclick="0" style="margin-right:.5em;"><i class="fa fa-plus-square-o fa-2"></i></span>' : '') + data[i].ProductTypeName + ' </span></td>' +
                               
                                '<td>' + data[i].CreatedDateName + '</td>' +
                                '<td>' + data[i].UpdatedDateFormate + '</td>' +

                              '<td>' +
                                    '<span class="btn btn-success btn_pro_type_Edit" data-id="' + data[i].ProductTypeId + '"><i class="fa fa-pencil"></i></span> ' + ' ' +
                                    ((data[i].HasChild == 'False') ? '<span class="btn btn-danger btn_pro_type_Delete" data-id="' + data[i].ProductTypeId + '" data-name="' + data[i].ParentName + '"><i class="fa fa-trash"></i></span>' : '') + ' ' +
                                    '<span class="btn btn-info fa-2 btn_protype_child_add" data-id="' + data[i].ProductTypeId + '" data-name="' + data[i].ProductTypeName + '"><i class="fa fa-plus-circle"></i></span>' +
                                '</td>' +
                              '</tr>').insertAfter("#tr_" + typeId);

                            $("#spanForName_" + data[i].ProductTypeId).css("padding-left", (getPadValue + 15) + "%");

                        }
                    }
                }
            });
        }
        else {
            $(this).data("isclick", "0");
            $(this).attr("dataisclick", "0");
            $(".trforchild_" + typeId).each(function () {
                var id = $(this).data("proid");
                var haschild = $(this).data("prochild");
                if (haschild == "True") {
                    childremove(id);
                }
            });
            $(".trforchild_" + typeId).remove();
        }
    });
    function childremove(id) {
        $(".trforchild_" + id).each(function () {
            var nextChild = $(this).data("proid");
            var haschild = $(this).data("prochild");
            if (haschild == "True") { childremove(nextChild); }
        });
        $(".trforchild_" + id).remove();
    }

    $("#btn_protype_create").click(function () {
        var window = $("#window").data("kendoWindow");
        window.setOptions({
            width: '35%',
            title: 'Create New Product Type'
        });
        window.refresh({
            url: "/Soldier/ProductTypeCreate"
        });
        window.center();
        window.open();
    });
    $("#divForAll_Pro_type").on("click", ".btn_protype_child_add", function (e) {
        e.preventDefault();
        var window = $("#window").data("kendoWindow");
        var parent = $(this).data("id");
        var typeName = $(this).data("name");
        window.setOptions({
            width: '60%',
            height: '25%',
            title: 'Add New Sub Product Type'
        });
        window.refresh({
            url: "/Soldier/ProductTypeCreate?ParentId=" + parent + '&ParentName=' + typeName
        });
        window.center();
        window.open();
    });
    $("#divForAll_Pro_type").on("click", ".btn_pro_type_Edit", function (e) {
        e.preventDefault();
        var window = $("#window").data("kendoWindow");
        var typeId = $(this).data("id");
        window.setOptions({
            width: '35%',
            title: 'Update Product Type Information'
        });
        window.refresh({
            url: "/Soldier/ProductTypeCreate?ProductTypeId=" + typeId
        });
        window.center();
        window.open();
    });
    $("#divForAll_Pro_type").on("click", ".btn_pro_type_Delete", function (e) {
        if (confirm('Are you sure want to delete this product type?')) {
            e.preventDefault();
            var typeId = $(this).data("id");
            var parentName = $(this).data("name");

            notification.show({ message: "Deleting Product Type", showTime: startTime() }, "upload-progress");

            $.ajax({
                url: '@Url.Action("ProductTypeDestroy", "Soldier")',
                type: 'Post',
                data: { ProductTypeId: typeId, UserId: userId, ParentName: parentName },
                success: function (data) {
                    notification.hide();
                    notification.setOptions({ autoHideAfter: 5000 });
                    if (data === "Success") {

                        notification.show({ message: "Product type successfully deleted", showTime: startTime() }, "upload-success");

                        $("#divForAll_Pro_type").empty();
                        $("#divForAll_Pro_type").append('<div class="loading_partial"></div>');
                        $("#divForAll_Pro_type").load('@Url.Action("_ShowAllProductTypeList", "Soldier")');
                    }
                    else {
                        var msg = (data === "Error") ? "Product type delete attempt unsuccessful." : "Product type delete attempt unsuccessful, " + data;
                        notification.show({ message: msg, showTime: startTime() }, "upload-error");
                    }
                }
            });
        }
    });
</script>

FactoryManagement/Views/Soldier/_ShowAllProductTypeList.cshtml
@************************************** Created By Mabia Mishu (Date:01.09.2016)  ***************************************@

@{
    var count = 1;
    FactoryManagement.Models.FactoryManagementEntities db = new FactoryManagement.Models.FactoryManagementEntities();
}

<table class="table table-bordered table-condensed tableForProductTypeList">
    <tbody>
        <tr>
            <th width="20%">Name</th>
            <th width="15%">Created Date</th>
            <th width="15%">Last Updated Date</th>
            <th width="10%"></th>
        </tr>
        @foreach (var item in ViewBag.AllParentProType as IEnumerable<FactoryManagement.ModelView.Inventory.Product.ProductTypeViewModel>)
        {
            <tr id="tr_@item.ProductTypeId">
                <td>
                    <span>@count. </span>
                    <span id="spanForName_@item.ProductTypeId">
                        @if (item.HasChild == "True")
                        {
                            <span class="btn_expandProductType" id="newtrForAp_@item.ProductTypeId"
                                  data-id="@item.ProductTypeId"
                                  data-isclick="0">
                                <i class="fa fa-plus-square-o fa-2"></i>
                            </span>

                        }
                        <span>@Html.DisplayFor(modelItem => item.ProductTypeName)</span>
                    </span>
                </td>
                <td>@Html.DisplayFor(modelItem => item.CreatedDateName)</td>
                <td>@Html.DisplayFor(modelItem => item.UpdatedDateFormate)</td>
                <td>
                    <span class="btn btn-success btn_pro_type_Edit" data-id="@item.ProductTypeId"><i class="fa fa-pencil"></i></span>
                    <span class="btn btn-info btn_protype_child_add" data-name="@item.ProductTypeName" data-id="@item.ProductTypeId"><i class="fa fa-plus-circle"></i></span>
                    <span class="btn btn-danger btn_pro_type_Delete" data-id="@item.ProductTypeId"><i class="fa fa-trash"></i></span>
                </td>
            </tr>
            count++;
        }

    </tbody>
</table>