FactoryManagement/Controllers/SuperAdminController.cs
using FactoryManagement.Models;
using FactoryManagement.ModelView.Configuration;
using FactoryManagement.ModelView.HR;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FactoryManagement.Controllers
{
    [Authorize]
    [DisplayName("Audit Logs")]
    public class SuperAdminController : Controller
    {
        #region Private Properties
        private FactoryManagementEntities db = new FactoryManagementEntities();
        int ShowItemPerPage = 50;
        static private int offset = Convert.ToInt32(ConfigurationManager.AppSettings["localTime"]);
        DateTime now = DateTime.UtcNow.AddMinutes(offset);
        #endregion

        public ActionResult AuditLog(bool IsOwn)
        {
            if (IsOwn)
            {
                ViewBag.TableName = new SelectList(db.View_Audit_Information.GroupBy(m => m.TableName)
                                                    .Select(t => new
                                                    {
                                                        Id = t.Select(w => w.TableName).FirstOrDefault(),
                                                        TableName = t.Select(w => w.TableName).FirstOrDefault()
                                                    }).OrderBy(o => o.TableName), "Id", "TableName");

                ViewBag.ModuleName = new SelectList(db.View_Audit_Information.GroupBy(m => m.ModuleName)
                                                    .Select(t => new
                                                    {
                                                        Id = t.Select(w => w.ModuleName).FirstOrDefault(),
                                                        ModuleName = t.Select(w => w.ModuleName).FirstOrDefault()
                                                    }).OrderBy(o => o.ModuleName), "Id", "ModuleName");
            }
            else
            {
                ViewBag.TableName = new SelectList(db.View_Audit_Information.GroupBy(m => m.TableName)
                                                    .Select(t => new
                                                    {
                                                        Id = t.Select(w => w.TableName).FirstOrDefault(),
                                                        TableName = t.Select(w => w.TableName).FirstOrDefault()
                                                    }).OrderBy(o => o.TableName), "Id", "TableName");
                ViewBag.ModuleName = new SelectList(db.View_Audit_Information.GroupBy(m => m.ModuleName)
                                                   .Select(t => new
                                                   {
                                                       Id = t.Select(w => w.ModuleName).FirstOrDefault(),
                                                       ModuleName = t.Select(w => w.ModuleName).FirstOrDefault()
                                                   }).OrderBy(o => o.ModuleName), "Id", "ModuleName");
            }
            ViewBag.IsOwn = IsOwn;
            return View();
        }
        public PartialViewResult _AuditLog(int? days, bool IsOwn, long userId)
        {
            var allAudit = db.View_Audit_Information.OrderByDescending(m => m.OperationStatus).ThenByDescending(m=>m.Date).ToList();
            if (IsOwn)
            {
                allAudit = allAudit.Where(m => m.UserId == userId).ToList();
            }
            if (days > 0)
            {
                DateTime countDate = now.Date;
                int day = Convert.ToInt32(days);
                if (day > 1)
                {
                    countDate = countDate.AddDays(-(day));
                    allAudit = allAudit.Where(m => m.Date > countDate).ToList();
                }
            }
            Session["AllAduitList"] = allAudit;
            Session["TotalAduitCount"] = allAudit.Count();
            ViewBag.Count = allAudit.Count();
            ViewBag.list = allAudit.Take(ShowItemPerPage).ToList();
            return PartialView(ViewBag.list);
        }
        public PartialViewResult _AuditLogForSpecificUser(string moduleName, long eventDoneBy)
        {
            var allAudit = db.View_Audit_Information.Where(m => m.UserId == eventDoneBy).OrderByDescending(m => m.Date).ToList();
            if (moduleName != "")
            {
                allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
            }
            Session["AllAduitList"] = allAudit;
            Session["TotalAduitCount"] = allAudit.Count();
            ViewBag.Count = allAudit.Count();
            ViewBag.list = allAudit.Take(ShowItemPerPage).ToList();
            return PartialView("_AuditLog", ViewBag.list);
        }
        public PartialViewResult _AuditLogStatus(int status, long? eventDoneBy,string moduleName, long userId, bool IsOwn)
        {
            if (status == 1)
            {
                var list = db.View_Audit_Information.OrderByDescending(m => m.OperationStatus).ThenByDescending(m => m.Date).ToList();
                Session["AduitListModule"] = list;
            }
            else
            {
                var list = db.View_Audit_Information.OrderBy(m => m.OperationStatus).ThenByDescending(m => m.Date).ToList();
                Session["AduitListModule"] = list;
            }
            var allAudit = (List<View_Audit_Information>)Session["AduitListModule"];
            if (eventDoneBy != null)
            {
                allAudit = db.View_Audit_Information.Where(m => m.UserId == eventDoneBy).OrderByDescending(m => m.OperationStatus).ThenByDescending(m => m.Date).ToList();
                if (moduleName != "")
                {
                    allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                }                
            }
            else
            {
                if (IsOwn)
                {
                    allAudit = db.View_Audit_Information.Where(m => m.UserId == userId).OrderByDescending(m => m.OperationStatus).ThenByDescending(m => m.Date).ToList();
                    if (moduleName != "")
                    {
                        allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                    }                  
                }
                else
                {
                    allAudit = db.View_Audit_Information.OrderByDescending(m => m.OperationStatus).ThenByDescending(m => m.Date).ToList();
                    if (moduleName != "")
                    {
                        allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                    }
                }
            }
            Session["AllAduitList"] = allAudit;
            Session["TotalAduitCount"] = allAudit.Count();
            ViewBag.Count = allAudit.Count();
            ViewBag.list = allAudit.Take(ShowItemPerPage).ToList();
            return PartialView("_AuditLog", ViewBag.list);
        }
        public PartialViewResult _AuditModuleChange(string moduleName,long? eventDoneBy, long userId, bool IsOwn)
        {
            if (moduleName == "")
            {
                var list = db.View_Audit_Information.OrderByDescending(m => m.Date).ToList();
                Session["AduitListModule"] = list;
            }
            else
            {
                var list = db.View_Audit_Information.Where(m => m.ModuleName == moduleName).OrderByDescending(m => m.Date).ToList();
                Session["AduitListModule"] = list;
            }
            var allAudit = (List<View_Audit_Information>)Session["AduitListModule"];
            if (eventDoneBy > -1)
            {
                allAudit = allAudit.Where(m => m.UserId == eventDoneBy).OrderByDescending(m => m.Date).ToList();
                if (moduleName != "")
                {
                    allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                }
            }
            else
            {
                if (IsOwn)
                {
                    allAudit = allAudit.Where(m => m.UserId == userId).OrderByDescending(m => m.Date).ToList();
                    if (moduleName != "")
                    {
                        allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                    }
                }
                else
                {
                    allAudit = allAudit.OrderByDescending(m => m.Date).ToList();
                    if (moduleName != "")
                    {
                        allAudit = allAudit.Where(m => m.ModuleName == moduleName).ToList();
                    }
                }
            }
            Session["AllAduitList"] = allAudit;
            Session["TotalAduitCount"] = allAudit.Count();
            ViewBag.Count = allAudit.Count();
            ViewBag.list = allAudit.Take(ShowItemPerPage).ToList();
            return PartialView("_AuditLog", ViewBag.list);
        }
        public PartialViewResult _AuditDayWise(int days,string moduleName, long? eventDoneBy, long userId, bool IsOwn)
        {
            DateTime countDate = DateTime.Today;
            var allAudit = db.View_Audit_Information.OrderByDescending(m => m.Date).ToList();
            int day = Convert.ToInt32(days);
            if (day > 1)
            {
                countDate = countDate.AddDays(-(day));      
            }
            if (day > 0)
            {
                allAudit = allAudit.Where(m => m.Date > countDate).OrderByDescending(m => m.Date).ToList();
            }
            if (eventDoneBy > -1)
            {
                allAudit = allAudit.Where(m => m.UserId == eventDoneBy).OrderByDescending(m => m.Date).ToList();
                if (moduleName != "")
                {

FactoryManagement/Views/SuperAdmin/AuditLogDetails.cshtml
@model FactoryManagement.Models.AuditInformation

@{
    ViewBag.Title = "AuditLogDetails";
    Layout = "~/Views/Shared/_LayoutForTemplate.cshtml";
}
<h3 class="page-title">Audit Log Details</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-basket"></i>
            <a href="javascript:;">Inventory</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <i class="fa fa-th-list"></i>
            <a href="/SuperAdmin/AuditLog?IsOwn=true">Activity Log</a>
        </li>
        <li>
            <i class="fa fa-info-circle"></i>
            <span>Audit Log Details</span>
        </li>
    </ul>
</div>
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-green">
            <i class="fa fa-plus font-green"></i>
            <span class="caption-subject green bold uppercase">Audit Log Details</span>
        </div>
    </div>
    <div class="portlet-body form">
        <dl class="dl-horizontal">
            <dt>Operation Name</dt>
            <dd>@Html.DisplayFor(model => model.OperationName)</dd>

            <dt>Message</dt>
            <dd>@Html.DisplayFor(model => model.Message)</dd>

            <dt>Module Name</dt>
            <dd>@Html.DisplayFor(model => model.ModuleName)</dd>

            <dt>Page Name</dt>
            <dd>@Html.DisplayFor(model => model.PageName)</dd>

            <dt>Database Table Name</dt>
            <dd>@Html.DisplayFor(model => model.TableName)</dd>

            <dt>Database ColumnId</dt>
            <dd>@Html.DisplayFor(model => model.ColumnId)</dd>

            <dt>Date</dt>
            <dd>@Convert.ToDateTime(Model.Date).ToString("dddd,  dd MMMM yyyy  h:mm tt")</dd>

            <dt>Operation Status</dt>
            <dd>@if (Model.OperationStatus == 1)
            { <span>Succeed</span>}
            else
            {<span>Failed</span>}</dd>

            <dt>Operation Done By</dt>
            <dd>
                @if (Model.UserId > 0)
                {
                    long id = Convert.ToInt64(Model.UserId);
                    FactoryManagement.Models.FactoryManagementEntities db = new FactoryManagement.Models.FactoryManagementEntities();
                    var user = db.View_UserLists.Where(m => m.UserType == 1 && m.UserId == id).FirstOrDefault();
                    <img src="~/Images/UserPicture/thumb/@user.Picture" class="user-photo" />
                    <span>@user.UserName</span>

                }
                else
                {
                    <img src="~/Images/UserPicture/thumb/admin.jpg" class="user-photo" /><span>Super Admin</span>
                }
            </dd>

        </dl>


        @*<h3>
            @Model.Name
            <span style="float:right;">
                @if (Model.VoucherStatus == 0)
                {
                    <span class="btn green" data-toggle="tooltip" title="Approve Manual Indent" data-container="body" id="btn_app_indent_voucher"><i class="fa fa-check"></i></span>
                }
            </span>
        </h3>
        <p>
            @if (Model.CreatedBy > 0)
            {
                <span>Created By : @db.View_UserLists.Where(m => m.UserId == Model.CreatedBy).Select(m => m.UserName).FirstOrDefault()</span>
            }
            else
            {
                <span>Created By : Super Admin</span>
            }
        </p>
        <p>Created Date : @Convert.ToDateTime(Model.CreatedDate).ToString("MMM dd, yy")</p>
        <p>
            Status : @if (Model.VoucherStatus == 0)
            { <span class="text-center text-warning">Pending Approval</span>}
            else if (Model.VoucherStatus == 1)
            { <span class="text-center text-info bold">Partial</span>}
            else if (Model.VoucherStatus == 2)
            {<span class="text-center text-success">Completed</span>}
            else
            {<span class="text-center text-danger">Deleted</span>}
        </p>*@

    </div>
</div>

FactoryManagement/Views/SuperAdmin/_AuditLog.cshtml
@{
    var count = 0;
}
<table class="table table-bordered" id="tbl_Audit_List">
    <tbody>
        <tr >
            <th width="5%">#</th>
            <th width="15%">Operation</th>
            <th width="10%">Module Name</th>
            <th width="10%">Status <span class="" id="btn_icon"></span> </th>
            <th width="15%">Time</th>
            <th width="20%">Event Intiated By</th>
        </tr>

        @foreach (var item in ViewBag.list as IEnumerable<FactoryManagement.Models.View_Audit_Information>)
        {
            count++;
            <tr>
                <th scope="row">@count</th>
                <td>
                    @if (item.OperationStatus == 1)
                    {<i class="fa fa-info-circle"></i> }
                    else
                    {<i class="fa fa-exclamation-circle" style="color:#ff6a00;"></i>}
                    <a href="/SuperAdmin/AuditLogDetails/@item.Id">@item.OperationName</a>
                </td>
                <td>@item.ModuleName</td>
                <td>@item.OpStatusValue</td>
                <td>@item.OperationTime</td>
                <td>
                    <img src="~/Images/UserPicture/thumb/@item.PictureName" class="img-circle" />
                    <span>@item.UserName</span>
                </td>
            </tr>         
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        totalCount = '@(ViewBag.Count)';
        showCount = '@count';
        $("#spn_total").text('@(ViewBag.Count)');
        if (up) {
            $("#btn_icon").addClass('k-icon k-i-arrow-n');
        }
        else {
            $("#btn_icon").addClass('k-icon k-i-arrow-s');
        }
    });

    $("#btn_icon").click(function () {
        page = 0, showCount = 0, totalCount = 0;
        if (up) {
            $("#Div_Partial_load").empty();
            $("#Div_Partial_load").append('<div class="loading_partial"></div>');
            var sendData = '';
            if (eventDoneBy > -1) {
                sendData = { status: -1,eventDoneBy:eventDoneBy,moduleName:moduleName, isOwn: false, userId: userId };
            } else {
                sendData = { status: -1,moduleName:moduleName,isOwn: isOwn, userId: userId };
            }
            $("#Div_Partial_load").load('@Url.Action("_AuditLogStatus", "SuperAdmin")',sendData);
            up = false;
        } else {
            $("#Div_Partial_load").empty();
            $("#Div_Partial_load").append('<div class="loading_half"></div>');
            var sendData = '';
            if (eventDoneBy > -1) {
                sendData = { status: 1, eventDoneBy: eventDoneBy, moduleName: moduleName, isOwn: false, userId: userId };
            } else {
                sendData = { status: 1, moduleName: moduleName, isOwn: isOwn, userId: userId };
            }
            $("#Div_Partial_load").load('@Url.Action("_AuditLogStatus", "SuperAdmin")',sendData);
            up = true;
        }
    });
</script>